### ISSUE TITLE
Apache logs from the civicrm container do not propogate to the host

### ISSUE THREAD

**Issue by michaelmcandrew** [michaelmcandrew/civicrm-buildkit-docker#12]
amp defines a custom log file for apache that prevents Docker from handling the logs. See https://github.com/amp-cli/amp/issues/52 for more details.

As soon as https://github.com/civicrm/civicrm-buildkit/pull/396 is merged, we can create a new Docker image based on a newer version of buildkit that uses the custom vhost and config added in this commit: https://github.com/michaelmcandrew/civicrm-buildkit-docker/commit/65a0971e4cdb2beb0a5f88880540fe2879c896f0.

Until then, a workaround is to manually edit the vhost files in /buildkit/.amp/apache.d and remove the lines that define the custom logs.

**Comment by totten** [comment]
The dependency https://github.com/civicrm/civicrm-buildkit/pull/396 is now merged.

**Comment by michaelmcandrew** [comment]
thanks @totten - closing this issue now.
