### ISSUE TITLE
HTTP error 403 at http://localhost:8080 after startup

### ISSUE THREAD

**Issue by xurizaemon** [michaelmcandrew/civicrm-buildkit-docker#18]
Hey - I wonder if this is related to #17 ?

    ~/D/civicrm-buildkit-docker (master|✔) $ docker-compose up -d
    Creating network "civicrmbuildkitdocker_default" with the default driver
    Creating civicrmbuildkitdocker_mysql_1   ... done
    Creating civicrmbuildkitdocker_maildev_1 ... done
    Creating civicrmbuildkitdocker_civicrm_1    ... done
    Creating civicrmbuildkitdocker_phpmyadmin_1 ... done

    ~/D/civicrm-buildkit-docker (master|✔) $ curl --head http://localhost:8080
    HTTP/1.1 403 Forbidden
    Date: Fri, 27 Apr 2018 10:41:45 GMT
    Server: Apache/2.4.10 (Debian)
    Content-Type: text/html; charset=iso-8859-1

Same result by browser - I'm confident this is the docker/civi combo I'm being rejected by (ie not another docker or local server).

uid=501, OSX

**Comment by xurizaemon** [comment]
> [Fri Apr 27 10:41:45.234188 2018] [autoindex:error] [pid 17] [client 172.20.0.1:50366] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive

**Comment by xurizaemon** [comment]
lol I didn't read the instructions to step 2 🍷 

    docker-compose exec -u buildkit civicrm civibuild create dmaster --url http://localhost:8080

**Comment by michaelmcandrew** [comment]
glad you got it working :)
