### ISSUE TITLE
drupal-clean type not working?

### ISSUE THREAD

**Issue by lolcodeca** [michaelmcandrew/civicrm-buildkit-docker#24]
The below command is giving me a populated DB rather than an empty one:
docker-compose exec -u buildkit civicrm civibuild create drupal_clean --type drupal-clean  --url http://localhost:8080 --civi-ver 5.3

It's been a while since I used civibuild so I may be missing something.

**Comment by lolcodeca** [comment]
Also thanks for this tool. Zero to Civi in 5 minutes!

**Comment by michaelmcandrew** [comment]
I also get demo data. My hunch is that this is a core civicrm or civicrm-buildkit issue rather than civicrm-buildkit-docker.

Have you tried a similar command on buildkit setup built outside of civicrm-buildkit-docker?

**Comment by michaelmcandrew** [comment]
closing since i didn't hear back from you. feel free to let me know how you got on...
