### ISSUE TITLE
error while building a new site

### ISSUE THREAD

**Issue by asymptotes** [michaelmcandrew/civicrm-buildkit-docker#28]
+++ amp create -f --root=/buildkit/build/dmaster --name=cms --prefix=CMS_ --url=http://localhost:8080 --output-file=/tmp/ampvarfMwTP0 --perm=admin
PHP Error:  Call to a member function getDriver() on null in phar:///buildkit/bin/amp/src/Amp/Database/MySQL.php on line 58
PHP Stack trace:
PHP   1. {main}() /buildkit/bin/amp:0
PHP   2. require() /buildkit/bin/amp:10
PHP   3. Amp\Application::main() phar:///buildkit/bin/amp/bin/amp:18
PHP   4. Amp\Application->run() phar:///buildkit/bin/amp/src/Amp/Application.php:59
PHP   5. Amp\Application->doRun() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Application.php:124
PHP   6. Amp\Application->doRunCommand() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Application.php:193
PHP   7. Amp\Command\CreateCommand->run() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Application.php:889
PHP   8. Amp\Command\CreateCommand->execute() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP   9. Amp\InstanceRepository->create() phar:///buildkit/bin/amp/src/Amp/Command/CreateCommand.php:107
PHP  10. Amp\Database\MySQL->createDatasource() phar:///buildkit/bin/amp/src/Amp/InstanceRepository.php:48

Error: Call to a member function getDriver() on null in phar:///buildkit/bin/amp/src/Amp/Database/MySQL.php on line 58

Call Stack:
    0.0010     354008   1. {main}() /buildkit/bin/amp:0
    0.0129     543656   2. require('phar:///buildkit/bin/amp/bin/amp') /buildkit/bin/amp:10
    0.0148     847880   3. Amp\Application::main() phar:///buildkit/bin/amp/bin/amp:18
    0.0419    3153608   4. Amp\Application->run() phar:///buildkit/bin/amp/src/Amp/Application.php:59
    0.0421    3157064   5. Amp\Application->doRun() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Application.php:124
    0.0422    3157064   6. Amp\Application->doRunCommand() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Application.php:193
    0.0422    3155696   7. Amp\Command\CreateCommand->run() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Application.php:889
    0.0424    3159000   8. Amp\Command\CreateCommand->execute() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
    0.0443    3370736   9. Amp\InstanceRepository->create() phar:///buildkit/bin/amp/src/Amp/Command/CreateCommand.php:107
    0.0443    3370776  10. Amp\Database\MySQL->createDatasource() phar:///buildkit/bin/amp/src/Amp/InstanceRepository.php:48

PHP Fatal error:  Uncaught Error: Call to a member function getDriver() on null in phar:///buildkit/bin/amp/src/Amp/Database/MySQL.php:58
Stack trace:
#0 phar:///buildkit/bin/amp/src/Amp/InstanceRepository.php(48): Amp\Database\MySQL->createDatasource('dmastercms')
#1 phar:///buildkit/bin/amp/src/Amp/Command/CreateCommand.php(107): Amp\InstanceRepository->create(Object(Amp\Instance), true, true, 'admin')
#2 phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(252): Amp\Command\CreateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application in phar:///buildkit/bin/amp/src/Amp/Database/MySQL.php on line 58

Fatal error: Uncaught Error: Call to a member function getDriver() on null in phar:///buildkit/bin/amp/src/Amp/Database/MySQL.php on line 58

Error: Call to a member function getDriver() on null in phar:///buildkit/bin/amp/src/Amp/Database/MySQL.php on line 58

Call Stack:
    0.0010     354008   1. {main}() /buildkit/bin/amp:0
    0.0129     543656   2. require('phar:///buildkit/bin/amp/bin/amp') /buildkit/bin/amp:10
    0.0148     847880   3. Amp\Application::main() phar:///buildkit/bin/amp/bin/amp:18
    0.0419    3153608   4. Amp\Application->run() phar:///buildkit/bin/amp/src/Amp/Application.php:59
    0.0421    3157064   5. Amp\Application->doRun() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Application.php:124
    0.0422    3157064   6. Amp\Application->doRunCommand() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Application.php:193
    0.0422    3155696   7. Amp\Command\CreateCommand->run() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Application.php:889
    0.0424    3159000   8. Amp\Command\CreateCommand->execute() phar:///buildkit/bin/amp/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
    0.0443    3370736   9. Amp\InstanceRepository->create() phar:///buildkit/bin/amp/src/Amp/Command/CreateCommand.php:107
    0.0443    3370776  10. Amp\Database\MySQL->createDatasource() phar:///buildkit/bin/amp/src/Amp/InstanceRepository.php:48

**Comment by michaelmcandrew** [comment]
What command did you execute to produce the above?

Can you log into the civicrm container and run `amp test`?

**Comment by asymptotes** [comment]
I followed instruction at https://docs.civicrm.org/dev/en/latest/tools/buildkit/
I got this error when i try to create a new site using docker-compose exec -u buildkit civicrm civibuild create dmaster --url http://localhost:8080
I haven't done amp test, i will update you

**Comment by asymptotes** [comment]
More over i got to this stage by changing the docker-compose file version to 2.

**Comment by michaelmcandrew** [comment]
> More over i got to this stage by changing the docker-compose file version to 2.
That is likely to cause errors.
What version of docker and docker compose are you using?

**Comment by asymptotes** [comment]
docker version 18.06.1-ce, build e68fc7a
docker-compose version docker-compose version 1.8.0, build unknown

**Comment by michaelmcandrew** [comment]
Ok, try upgrading docker compose to 3+

**Comment by michaelmcandrew** [comment]
closing since i didn't hear back from you. feel free to let me know how you got on...

**Comment by joemcl** [comment]
hey @asymptotes wondering if you figured out the answer - I'm getting the same error, though I'm not using the docker version of buildkit....

**Comment by joemcl** [comment]
and @michaelmcandrew FYI I'm running ```docker-compose version 1.21.0, build unknown``` and just for the heck of it, will update to docker-compose v 3+

**Comment by joemcl** [comment]
@michaelmcandrew @asymptotes FYI see this on StackExchange - https://civicrm.stackexchange.com/questions/31928/mysql-dsn-error-on-amp-config-why-am-i-getting-access-denied?noredirect=1#comment36385_31928 .
