### ISSUE TITLE
Personal diffculty with locating CiviCRM core after sucesfull build

### ISSUE THREAD

**Issue by prondubuisi** [michaelmcandrew/civicrm-buildkit-docker#38]
Hello @michaelmcandrew I have successfully installed CiviCRM using this buildkit. Now I am confused as I don't know where the CiviCRM core folders are pulled in. I will appreciate any help with this please. 
![Civi SIte](https://user-images.githubusercontent.com/22311928/56011908-cd1ae680-5ce1-11e9-8f6a-eb642db35411.png)
![VS code](https://user-images.githubusercontent.com/22311928/56011913-d7d57b80-5ce1-11e9-840d-d5e176e72f5b.png)

**Comment by michaelmcandrew** [comment]
hi @prondubuisi - looks like you are nearly there. Try expanding that dmaster folder you have highlighted in the sidebar.
CiviCRM core files should be in `build/dmaster/sites/all/modules/civicrm`.

**Comment by prondubuisi** [comment]
Hello @michaelmcandrew this works. I am trying to pull the latest commits to CiviCRM core and I am getting this 

`coolife@coolife:~/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm$ git pull origin master 
From https://github.com/civicrm/civicrm-core
 * branch                  master     -> FETCH_HEAD
Updating f20312c9f6..0dcf3c833a
error: Your local changes to the following files would be overwritten by merge:
	CONTRIBUTORS.txt
	CRM/ACL/API.php
	CRM/ACL/BAO/ACL.php
	CRM/ACL/BAO/Cache.php
	CRM/ACL/BAO/EntityRole.php
	CRM/ACL/DAO/ACL.php
	CRM/ACL/DAO/Cache.php
	CRM/ACL/DAO/EntityRole.php
	CRM/ACL/Form/ACL.php
	CRM/ACL/Form/ACLBasic.php
	CRM/ACL/Form/EntityRole.php
------
`
any idea how I can fix this and then pull latest commits

**Comment by michaelmcandrew** [comment]
@prondubuisi this doesn't sound like it is a civicrm-buildkit-docker specific question. More of a general buildkit / civicrm development question. Try asking for help here: https://chat.civicrm.org/civicrm/channels/dev or https://chat.civicrm.org/civicrm/channels/dev-newcomers
