### ISSUE TITLE
exec: "docker-civicrm-entrypoint": executable file not found in $PATH during docker-compose up

### ISSUE THREAD

**Issue by lediur** [michaelmcandrew/civicrm-buildkit-docker#43]
I'm running into an issue with the Docker Hub published `michaelmcandrew/civicrm-buildkit` image. I believe it's the latest published image from 2 hours ago since I ran `docker-compose pull` quite recently.

```
Creating network "crm_default" with the default driver
Creating crm_mysql_1 ...
Creating crm_mysql_1 ... done                                                                                           Creating crm_civicrm_1 ...
Creating crm_civicrm_1 ... error                                                                                        
ERROR: for crm_civicrm_1  Cannot start service civicrm: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"docker-civicrm-entrypoint\": executable file not found in $PATH": unknown

ERROR: for civicrm  Cannot start service civicrm: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"docker-civicrm-entrypoint\": executable file not found in $PATH": unknown
ERROR: Encountered errors while bringing up the project.
```

Is the entrypoint file `chmod +x`'d? I didn't notice a line to do that in the Dockerfile.

**Comment by lediur** [comment]
In the custom build PHP 7.3 Dockerfile, I added a `RUN chmod +x /usr/local/bin/docker-civicrm-entrypoint` line near the end of the file after the entrypoint script was copied into the image. This seemed to resolve the issue and allowed me to run the container.

**Comment by michaelmcandrew** [comment]
@lediur - thanks for investigating and for the fix!

I've updated the repo here: https://github.com/michaelmcandrew/civicrm-buildkit-docker/commit/55a202b2bceb57acf705ffc23a2f26aacb78afc1 and will start the build process again. If you were able to test the php7.3 image in a few hours time to make sure that the fix has found its way into the final build, that would be ace.

**Comment by lediur** [comment]
Yep, confirmed that I was able to `docker-compose up` the pulled image. Thanks for the fix!

**Comment by michaelmcandrew** [comment]
great - thanks!
