### ISSUE TITLE
xdebug is loaded twice

### ISSUE THREAD

**Issue by wmortada** [michaelmcandrew/civicrm-buildkit-docker#46]
When I run a command such as `bkc civibuild create` I get multiple warning messages saying:

> Cannot load Xdebug - it was already loaded

I think this is because Xdebug is getting loaded twice. Once by buildkit.ini and once by debug.ini.

Removing the following line from buildkit.ini seems to fix this issue:

```
zend_extension=xdebug.so
```

**Comment by michaelmcandrew** [comment]
ta - your fix now merged.
