### ISSUE TITLE
Unable to start image on buster

### ISSUE THREAD

**Issue by wmortada** [michaelmcandrew/civicrm-buildkit-docker#60]
Following on from #56, I've had another issue trying to get buildkit running PHP 7.4. When I bring up the image I get the following error:

```
civicrm_1     | AH00526: Syntax error on line 2 of /buildkit/.amp/apache.d/localhost_7979.conf:
civicrm_1     | Cannot define multiple Listeners on the same IP:port
```

This seems to be an issue with a port conflict. I've tried running PHP 7.3 on buster and this also fails in the same way so I don't think it is anything to do with the PHP version. I wonder if this might be something to do with how apache works on buster?

Any ideas?

**Comment by wmortada** [comment]
Just tested again and this is still an issue.

**Comment by wmortada** [comment]
This is the offending file (`/buildkit/.amp/apache.d/localhost_7979.conf`) on debian stretch:

```
Listen 7979
<VirtualHost *:7979>
    ServerAdmin webmaster@localhost
    DocumentRoot "/buildkit/.amp/canary"

    ServerName localhost
    ErrorLog "/buildkit/.amp/log/localhost-7979.error_log"
    CustomLog "/buildkit/.amp/log/localhost-7979.access_log" common

    <Directory "/buildkit/.amp/canary">
        Options All
        AllowOverride All
        <IfModule mod_authz_host.c>
            Require all granted
        </IfModule>
    </Directory>

    
</VirtualHost>
```

**Comment by wmortada** [comment]
Comparing apache versions

* [Debian stretch has apache 2.4.25](https://packages.debian.org/stretch/apache2)
* [Debian buster has apache 2.4.38](https://packages.debian.org/buster/apache2)

**Comment by wmortada** [comment]
I'm wondering if this may be due to me having existing sites? When I get a chance I'll try a fresh install and see if that works.

**Comment by wmortada** [comment]
Okay, so clearing everything and starting again seems to have fixed this issue. I'm guessing there must have been a conflict in one of the existing files. I'm not sure which but it's working fine now.

In case this is an issue for others, I did the following:

- destroy all existing sites: `civibuild destroy [sitename]`
- destroy all related docker volumes: `docker volume rm civicrm-buildkit-docker_[volume name]`

**Comment by michaelmcandrew** [comment]
thanks for the report and for closing :)
