### ISSUE TITLE
Warning permission denied with log files

### ISSUE THREAD

**Issue by jaapjansma** [michaelmcandrew/civicrm-buildkit-docker#7]
I get the following warning on my civicrm installation build with this composer thing:

![screenshot from 2018-02-10 16-12-58](https://user-images.githubusercontent.com/4126292/36063463-7929bf82-0e7d-11e8-988d-f5148a18a3d3.png)

**Comment by michaelmcandrew** [comment]
Hey Jaap, what version are you using?

I created a [new apache based release over the weekend (0.3)](https://github.com/michaelmcandrew/civicrm-buildkit-docker/releases/tag/0.3.0) which fixes this issue.

**Comment by jaapjansma** [comment]
I dont know which version I am on but definitly not 0.3.0. I will try that one out and this issue can be closed then.

**Comment by michaelmcandrew** [comment]
Sure - I guess you were on the master branch with a commit older than Friday at least.

**Comment by jaapjansma** [comment]
Yeah I am on master. I checked it and updated to the latest master.

**Comment by michaelmcandrew** [comment]
OK - give me a shout if anything goes wrong - I am guessing you are the first person to try out this release.
