### ISSUE TITLE
NodeJS error when creating dmaster 

### ISSUE THREAD

**Issue by MarcMichalsky** [michaelmcandrew/civicrm-buildkit-docker#73]
Hi,
I get the following warnings when I create a new dmaster build:
```bash
WARNING: Failed to locate command "node". NodeJS (http://nodejs.org/) is required for development of CiviCRM v4.6+.
WARNING: Failed to locate command "npm". NodeJS (http://nodejs.org/) is required for development of CiviCRM v4.6+.
```
Later the building process fails at this point:
```bash
./bin/setup.sh: line 153: npm: command not found
```
-> [full log](https://gist.github.com/MarcMichalsky/dc80a9955e7060f02f9acc8bcc7aba63#file-dmaster_log)

Could this be related to issue #68 or PR #69?

**Comment by wmortada** [comment]
It sounds related to me but `node` and `npm` should be installed though (albeit an older version). Have you tried applying #69 to see if that helps?

**Comment by MarcMichalsky** [comment]
Hello @wmortada,
I tried your branch [wmortada:68-nodejs-outdated](https://github.com/wmortada/civicrm-buildkit-docker/tree/68-nodejs-outdated) with the same result.
-> [full log](https://gist.github.com/MarcMichalsky/dc80a9955e7060f02f9acc8bcc7aba63#file-dmaslter_log_68-nodejs-outdated)

**Comment by MarcMichalsky** [comment]
As a workaround I installed NodeJS and npm manually.
```bash
bkb
sudo apt update
sudo apt install npm
```

**Comment by wmortada** [comment]
Are you building your own container or using the one from Docker Hub? That branch will only make a difference if you are building your own container. If you could paste the commands you've used we can check.

**Comment by wmortada** [comment]
I'm wondering if the container on Docker Hub is missing `node`?

**Comment by michaelmcandrew** [comment]
I can replicate this, unfortunately.

I am presuming that `civi-download-tools` was not able to actually download node. I am running `docker build civicrm` and having a look at the output to see what went wrong...

**Comment by MarcMichalsky** [comment]
> Are you building your own container or using the one from Docker Hub? That branch will only make a difference if you are building your own container. If you could paste the commands you've used we can check.

Ouch! Didn't know that, sorry. Building the docker container on your [wmortada:68-nodejs-outdated](https://github.com/wmortada/civicrm-buildkit-docker/tree/68-nodejs-outdated) fixed the issue. Thanks!

**Comment by michaelmcandrew** [comment]
@MarcMichalsky - see https://github.com/michaelmcandrew/civicrm-buildkit-docker/issues/68#issuecomment-888315091 - a new docker hub should be published overnight now...
