### ISSUE TITLE
Tag of docker image, "new" not exist

### ISSUE THREAD

**Issue by rubofvil** [michaelmcandrew/civicrm-buildkit-docker#74]
I'm getting a error with `docker-compose up -d` the docker 

```
Creating network "civicrm-buildkit-docker_default" with the default driver
Pulling civicrm (michaelmcandrew/civicrm-buildkit:new)...
ERROR: manifest for michaelmcandrew/civicrm-buildkit:new not found: manifest unknown: manifest unknown
```

Line with the image
https://github.com/michaelmcandrew/civicrm-buildkit-docker/blob/master/docker-compose.yml#L4

In the tags available not appear the tag `new`
https://hub.docker.com/r/michaelmcandrew/civicrm-buildkit/tags?page=1&ordering=last_updated

**Comment by michaelmcandrew** [comment]
@rubofvil - sorry - that was a typo - now fixed :)

**Comment by michaelmcandrew** [comment]
please can you close this issue if that works for you

**Comment by rubofvil** [comment]
> please can you close this issue if that works for you

Thx! Works fine
